[build]
  # Build command
  command = "cd frontend && npm install && npm run build"
  
  # Directory to publish (output folder)
  publish = "frontend/build"
  
  # Base directory (where the build process will run)
  base = "."

[build.environment]
  # Node.js version
  NODE_VERSION = "18"
  
  # Environment variables
  REACT_APP_API_URL = "https://your-backend-api.netlify.app/api"

# Redirect rules for React Router (SPA)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for static assets caching
[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"

# 404 page
[[redirects]]
  from = "/404"
  to = "/index.html"
  status = 200